from abc import ABC, abstractmethod

class ILogger(ABC):
    @abstractmethod
    def info(self, msg: str): ...
    @abstractmethod
    def warn(self, msg: str): ...
    @abstractmethod
    def error(self, msg: str): ...
